# Pandas

## Pandas เป็นไลบราลี่ภาษา python สำหรับจัดการและวิเคราะห์ข้อมูลที่เป็นแบบโครงสร้างทั้งรูปแบบมิติเดียวกันและหลายมิติ
## โครงสร้างของ Pandas จะมี Series, DataFrame, Panel
### Series คือ เป็นโครงสร้างข้อมูลแบบ Array 1มิติ ที่เก็ฐข้อมูลต่างชนิดได้ มีส่วนประกอบ 2 ส่วน คือ
- Index ใช้อ้างอิงตำแหน่งของข้อมูล
- Element Value คือ ข้อมูลในแต่ละ Index

### DataFrame เป็นโครงสร้างข้อมูลแบบ Array 2มิติ (เป็นตารางประกอบด้วย 2 คอลัมขึ้นไป) หรือการนำ Series หลายๆอันมาต่อเรียงกัน เช่น ข้อมูลคะแนนนักเรียน ข้อมูลสินค้า หรือข้อมูลประชากร เป็นต้น

### Panel เป็นโครงสร้างจ้อมูลแบบ 3 มิติ เป็นการนำ DataFrame หลายๆชั้น ประกอบไปด้วย 3 แกน
- แกนที่ 0 - DataFrame
- แกนที่ 1 - แถวหรือ Index ของแต่ละ DataFrame
- แกนที่ 2 - คอลัมของแต่ละ DataFrame

## หัวข้อที่ 1 การสร้าง Series จาก List และ Tuple

In [5]:
import pandas as pd

data_ls = [10, 20, "Film", 15.05, "มะละกิ"] ##List
data_tp = (10, 20, "Film", 15.05, "มะละกอ") ##Tuple
sr = pd.Series(data_ls)
sr1 = pd.Series(data_tp)
print(sr)
print(f"\n{sr1}")

0        10
1        20
2      Film
3     15.05
4    มะละกิ
dtype: object

0        10
1        20
2      Film
3     15.05
4    มะละกอ
dtype: object

## สร้าง Series จาก Numpy

In [ ]:
import pandas as pd
import numpy as np

data_ls = [10, 20, "Film", 15.05, "มะละกอ"]##List
ndata = np.array(data_ls) #เอาข้อมูลที่เป็น list มาทำให้เป็น Numpy Array
ps = pd.Series(ndata) #นำข้อมูลเข้าจาก numpy มาเป็น Pandas Series
ps

0        10
1        20
2      Film
3     15.05
4    มะละกอ
dtype: object

## สร้าง Series แบบกำหนดเลข index

In [3]:
import pandas as pd
import numpy as np

items = ['องุ่น', 'กล้วย', 'มะละกอ']
idx = [50, 20, 30] #ก็คือ เลข 50 เนี้ยอะ คือ แทนด้วย องุ่น // 20 แทนด้วย กล้วย // 30 แทนด้วย มะละกอ
nitems = np.array(items)
ps = pd.Series(nitems, index=idx)
ps

50     องุ่น
20     กล้วย
30    มะละกอ
dtype: object

## สร้าง Series จาก Dictionary

In [6]:
import pandas as pd

data = {
    "กล้วย" : "banana",
    "มะละกอ" : "papaya",
    "องุ่น" : "grape"
}

ps = pd.Series(data)
ps

กล้วย     banana
มะละกอ    papaya
องุ่น      grape
dtype: object

## การเข้าถึงขอมูลใน Series (Dictionary)

In [11]:
import pandas as pd

data = {
    "กล้วย" : "banana",
    "มะละกอ" : "papaya",
    "องุ่น" : "grape"
}

ps = pd.Series(data)
ps["กล้วย"]
ps["มะละกอ"]
##หรือการเข้าถึงแบบ index
ps[0],ps[1]

/tmp/ipykernel_6330/3287430184.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ps[0],ps[1]

('banana', 'papaya')

## การเข้าถึงขอมูลใน Series (แบบช่วงข้อมูล Slice)
### โครงสร้างการเข้าถึง คือ
- ps[start:stop-1]

### สัญลักษณ์
- [:] คือ ทุกอัน
- [2:] คือ index ที่ 2 เป็นต้นไป
- [:2] คือ เริ่มตันไปจนก่อนถึง 2
- [1:3] คือ เริ่มต้นที่ index 1 ไปก่อนถึง index 3

In [17]:
import pandas as pd

ps = pd.Series([10, 20, 30, 40, 50, 60, 70, 80])
ps
##ต้องการตัวเลขที่มีค่ามากกว่าหรือเท่ากับ 40 จะทำได้โดย
print(f"มีค่ามากกว่า 40 \n{ps[3:]}")
print(f"\nเอาตัวเลขทุกตัวก่อนถึง index 4 = \n{ps[:4]}") #งั้นก็ว่า แสดงวิธีการหาโดย โดยนับจากเลข 0 ไปถึงยีงเห้องเลขที่มีค่าน้อยกว่า 1 index

มีค่ามากกว่า 40
3    40
4    50
5    60
6    70
7    80
dtype: int64

เอาตัวเลขทุกตัวก่อนถึง index 4 =
0    10
1    20
2    30
3    40
dtype: int64

## การสร้าง DataFrame จาก List และ Tuple

In [21]:
import pandas as pd

data_lst = ['10', '20', '30', '40']
data_tp = ('10', '20', '30', '40')

#ทำให้ดูสวยขึ้น
df = pd.DataFrame(data_lst)
df = pd.DataFrame(data_tp)
df #ใช้ได้ทั้งสอน

#แบบกำหนด คอลัม
data = [15, 20, 23, 30]
cols = ["age"]
df = pd.DataFrame(data, columns=cols)
df

   age
0   15
1   20
2   23
3   30

## การสร้าง DataFrame จาก List หลายมิติ

In [23]:
import pandas as pd

#List ซ้อน List
data = [["Fire Cookie", "Revice 10X", 498000],["Buddha Cookie", "Magcanic Aura", 498000],["Cheese Drop", "Base Speed 10%", 25400]]
sachdule = ["Name", "Ability", "Price"]

ps = pd.DataFrame(data, columns=sachdule)
ps

            Name         Ability   Price
0    Fire Cookie      Revice 10X  498000
1  Buddha Cookie   Magcanic Aura  498000
2    Cheese Drop  Base Speed 10%   25400

## การสร้าง DataFrame จาก List ด้วย zip

In [ ]:
import pandas as pd

#zip คือ การบีบอัดข้อมูล
#ต้องทำเป็นแบบเรียงชื่อกัน ภายใน list เลย เช่น list นี้เป็นชื่อ ก็ต้องเป็นชื่อให้หมด แล้วค่อยไปหัวข้อต่อไป
data1 = ["Cookie run classic", "Arena of valor", "PUBG"]
data2 = ["3M Downloads", "20M Downloads", "5M Downloads"]
data3 = ["First Chart", "Second Chart", "Tenth Chart"]

dtzip = list(zip(data1,data2,data3))
cols = ["Name", "Number of Downloads", "Number of Chart"]

ps = pd.DataFrame(dtzip, columns=cols)
ps

                 Name Number of Downloads Number of Chart
0  Cookie run classic        3M Downloads     First Chart
1      Arena of valor       20M Downloads    Second Chart
2                PUBG        5M Downloads     Tenth Chart

## สร้าง DataFrame จาก Dictionary

In [31]:
import pandas as pd

data = [
    {"Name" : "Film", "Study" : "NU", "Province" : "Phitsanulok"},
    {"Name" : "Pahan", "Study" : "NU", "Province" : "Phitsanulok"},
    {"Name" : "Nanay", "Study" : "PU", "Province" : "Payao"}
]

ps = pd.DataFrame(data)
ps

#ถ้าหากต้องการเอาชื่อสินค้ามาแทนตัวเลข index จะทำได้โดย
ps.set_index(["Name"])

      Study     Province
Name
Film     NU  Phitsanulok
Pahan    NU  Phitsanulok
Nanay    PU        Payao

## สร้าง DataFrame จาก Series

In [33]:
import pandas as pd

n = ["Drum", "Doll", "Computer"]
c = ["Music", "Toy", "Tecnology"]
p = [25000, 4000, 125000]

names = pd.Series(n)
categories = pd.Series(c)
prices = pd.Series(p)

datadict = {
    "Name" : names,
    "Category" : categories,
    "Price" : prices
}

ps = pd.DataFrame(datadict)
ps

       Name   Category   Price
0      Drum      Music   25000
1      Doll        Toy    4000
2  Computer  Tecnology  125000

## DataFrame ส่งออกเอกสาร CSV

### ทำได้โดย DataFrame.to_csv(ตำแหน่งไฟล์(Path), attribute)
### Attribute
- header ต้องการบันทึกส่วนหัวคอลัมน์หรือไม่ (True/False)(Dafault:True)
- index ต้องการบันทึกเลข index หรือไม่ (True/False)(Dafault:Ture)

In [ ]:
ps.to_csv("Pandas_Tutorial.csv") #โดยสร้างไฟล์ใหม่ และให้เก็บอยู่กับโฟลเดอร์เดียวกับ ไฟล์ที่ทำการส่งออก

## การอ่านเอกสาร CSV

import pandas as pd 

df = pd.read_csv("ตำแหน่งไฟล์", endcoding="utf-8")

df.head()

In [3]:
import pandas as pd

df = pd.read_csv("Pandas_Tutorial.csv", encoding="utf-8")
df

   Unnamed: 0      Name   Category   Price
0           0      Drum      Music   25000
1           1      Doll        Toy    4000
2           2  Computer  Tecnology  125000

## การอ่านเอกสาร csv บางคอลัมน์

import pandas as pd

df = pd.read("ตำแหน่งไฟล์")

cols = ["Name", "Price"]

df = pd.read_csv("ตำแหน่งไฟล์", endcoding="utf-8", usecols=cols)

df.head()

In [ ]:
import pandas as pd

cols = ["Name", "Price"] #อยากอ่านแค่ คอลัมน์ Name และ Price
df = pd.read_csv("Pandas_Tutorial.csv", encoding="utf-8", usecols=cols)
df

       Name   Price
0      Drum   25000
1      Doll    4000
2  Computer  125000

## การอ่านเอกสาร csv กำหนดหัวคอลัมน์

In [ ]:
import pandas as pd

#สำหรับไฟล์ที่ไม่ได้ตั้งชื่อ หรือตั้งชื่อคอลัมน์ของแต่ละคอลัมน์ (ใช้กับไฟล์ที่ไม่มีการกำหนดชื่อในนั้น นั้นเองง)
colsName = ["สินค้า", "หมวดหมู่", "ราคา"]
df = pd.read_csv("Pandas_Tutorial.csv", encoding="utf-8", names=colsName)
df

       สินค้า   หมวดหมู่    ราคา
NaN      Name   Category   Price
0.0      Drum      Music   25000
1.0      Doll        Toy    4000
2.0  Computer  Tecnology  125000

## การอ่านเอกสาร Excel

In [4]:
import pandas as pd

#สร้างตัวแปร เพื่ออ่านไฟล์ Excel ที่มีหลาย sheet และเลือก sheet ที่ต้องการ
df = pd.read_excel("dataupdate.xlsx", sheet_name="Product")
df

                 Name            Category    Price
0               เมาส์  อุปกรณ์คอมพิวเตอร์    900.0
1               ปากกา     อุปกรณ์การเรียน      NaN
2               โคมไฟ                 NaN      NaN
3            ไมโครโฟน                 NaN    750.0
4       เครื่องซักผ้า     เครื่องใช้ไฟฟ้า      NaN
5       เสื้อยืดคอกลม            เสื้อผ้า    500.0
6         กางเกงยีนต์            เสื้อผ้า      NaN
7       ตุ๊กตาหมีพูห์             ของเล่น    950.0
8                โซฟา        เฟอร์นิเจอร์   5000.0
9                 จาน         เครื่องครัว    250.0
10               ทีวี     เครื่องใช้ไฟฟ้า  15000.0
11              ยางลบ     อุปกรณ์การเรียน      NaN
12  External HardDisk  อุปกรณ์คอมพิวเตอร์   2500.0
13          คีย์บอร์ด  อุปกรณ์คอมพิวเตอร์    850.0
14           รถบังคับ             ของเล่น      NaN

## ตรวจสอบข้อมูล ใน DataFrame
- head() == อ่านข้อมูล 5 แถวแรก

- head(n) == อ่านข้อมูล n แถวแรก

- tail() == อ่านข้อมูล 5 แถวสุดท้าย

- tail(n) == อ่านข้อมูล n แถวสุดท้าย

- sample(n) == สุ่มจำนวนข้อมูล n แถว

- describe() == ดูค่าทางสถิติ เช่น ค่าต่ำสุด-สูงสุด ค่าเฉลี่ยข้อมูล เป็นต้น
    
    ดูค่าทางสถิติเบื้องต้น
    - mean() = ค่าเฉลี่ย
    - max() = ค่าสูงสุด
    - min() = ค่าน้อยสุด
    - count() = นับจำนวนข้อมูลทั้งหมด
    - std() = ส่วนเบี่ยงเบนมาตรฐาน
    - sum() = ผลรวมข้อมูล

- shape == สำหรับนับจำนวนข้อมูล เช่น (20, 4) คือ 20 แถว 4 คอลัมน์

- columns == ตรวจสอบว่ามีคอลัมน์อะไรบ้าง

- values == อ่านข้อมูลแบบ Array

## สภาพอากาศ

In [16]:
import pandas as pd

df = pd.read_excel("dataupdate.xlsx", sheet_name="weather")
df.head() #5 แถวแรก
df.tail() #5 แถวสุดท้าย
df.sample(5) #สุ่ม 5 แถว หรือ 5 วัน ==ถ้าไม่ใส่ตัวเลขก็จะสุ่ม 1 แถว==
df.describe() #สรุปข้อมูลเชิงสถิติของข้อมูลใน DataFrame
df.shape #แสดงขนาดของ DataFrame (จำนวนแถว, จำนวนคอลัมน์) ในที่นี้ คือ 30 แถว 4 คอลัมน์
df.columns #แสดงชื่อคอลัมน์ทั้งหมดใน DataFrame
df.values #แสดงค่าของ DataFrame ทั้งหมด บอกวันที่, อุณหภูมิสูงสุด, อุณหภูมิต่ำสุด, ปริมาณน้ำฝน

array([[Timestamp('2020-12-01 00:00:00'), 30, 9, 'แดดร้อน'],
       [Timestamp('2020-12-02 00:00:00'), 28, 8, 'เมฆมาก'],
       [Timestamp('2020-12-03 00:00:00'), 27, 4, 'ฝนตก'],
       [Timestamp('2020-12-04 00:00:00'), 19, 3, 'แดดร้อน'],
       [Timestamp('2020-12-05 00:00:00'), 20, 5, 'เมฆมาก'],
       [Timestamp('2020-12-06 00:00:00'), 25, 6, 'ฝนตก'],
       [Timestamp('2020-12-07 00:00:00'), 36, 4, 'ฝนตก'],
       [Timestamp('2020-12-08 00:00:00'), 28, 6, 'ฝนตก'],
       [Timestamp('2020-12-09 00:00:00'), 17, 5, 'เมฆมาก'],
       [Timestamp('2020-12-10 00:00:00'), 24, 6, 'แดดร้อน'],
       [Timestamp('2020-12-11 00:00:00'), 26, 4, 'ฝนตก'],
       [Timestamp('2020-12-12 00:00:00'), 27, 9, 'แดดร้อน'],
       [Timestamp('2020-12-13 00:00:00'), 30, 2, 'แดดร้อน'],
       [Timestamp('2020-12-14 00:00:00'), 31, 5, 'เมฆมาก'],
       [Timestamp('2020-12-15 00:00:00'), 28, 4, 'แดดร้อน'],
       [Timestamp('2020-12-16 00:00:00'), 27, 7, 'แดดร้อน'],
       [Timestamp('2020-12-17 00:00:00'), 20, 8, 'ฝนตก'],
       [Timestamp('2020-12-18 00:00:00'), 18, 5, 'ฝนตก'],
       [Timestamp('2020-12-19 00:00:00'), 25, 7, 'แดดร้อน'],
       [Timestamp('2020-12-20 00:00:00'), 28, 4, 'เมฆมาก'],
       [Timestamp('2020-12-21 00:00:00'), 25, 5, 'เมฆมาก'],
       [Timestamp('2020-12-22 00:00:00'), 38, 2, 'เมฆมาก'],
       [Timestamp('2020-12-23 00:00:00'), 34, 3, 'ฝนตก'],
       [Timestamp('2020-12-24 00:00:00'), 29, 4, 'ฝนตก'],
       [Timestamp('2020-12-25 00:00:00'), 34, 5, 'แดดร้อน'],
       [Timestamp('2020-12-26 00:00:00'), 25, 8, 'ฝนตก'],
       [Timestamp('2020-12-27 00:00:00'), 28, 9, 'เมฆมาก'],
       [Timestamp('2020-12-28 00:00:00'), 30, 2, 'เมฆมาก'],
       [Timestamp('2020-12-29 00:00:00'), 31, 1, 'ฝนตก'],
       [Timestamp('2020-12-30 00:00:00'), 35, 2, 'ฝนตก']], dtype=object)

## ชนิดข้อมูลและค่าทางสถิติ

In [19]:
import pandas as pd

data = ["Object", "int64", "float64", "Bool", "datetime64", "timedelta[ns]", "category",]
data1 = ["ชุดข้อความ(String), unicode", "จำนวนเต็ม", "จำนวนทศนิยม", "ค่าจริง/เท็จ", "วันที่และเวลา", "ค่าแตกต่างรหะหว่าง datetime", "หมวดหมู่(List ของขข้อความ)"]

dt = list(zip(data, data1))
cols = ["ชนิดข้อมูล", "คำอธิบาย"]

df = pd.DataFrame(dt, columns=cols)
df

      ชนิดข้อมูล                     คำอธิบาย
0         Object  ชุดข้อความ(String), unicode
1          int64                    จำนวนเต็ม
2        float64                  จำนวนทศนิยม
3           Bool                 ค่าจริง/เท็จ
4     datetime64                วันที่และเวลา
5  timedelta[ns]  ค่าแตกต่างรหะหว่าง datetime
6       category   หมวดหมู่(List ของขข้อความ)

In [26]:
import pandas as pd

df = pd.read_excel("dataupdate.xlsx", sheet_name="weather")
print(f"ค่ามากที่สุดของ Temperature: {df.Temperature.max()} องศา") #แสดงเฉพาะคอลัมน์ Temperature
print(f"ค่าน้อยที่สุดของ Temperature: {df.Temperature.min()} องศา")
print(f"ค่าเฉลี่ยของ Temperature: {df.Temperature.mean():.2f} องศา")

ค่ามากที่สุดของ Temperature: 38 องศา
ค่าน้อยที่สุดของ Temperature: 17 องศา
ค่าเฉลี่ยของ Temperature: 27.43 องศา

## การเลือกคอลัมน์และเลือกข้อมูลแบบช่วง

In [ ]:
import pandas as pd

df = pd.read_excel("dataupdate.xlsx", sheet_name="weather", index_col="Day")# กำหนดให้ Day เป็น index ของ DataFrame
df.Temperature
df.Temperature[:] #ต้องการเอาแถวทั้งหมดของคอลัมน์ Temperature เหมือนกับ df.Temperature
df.Temperature[1:6] #ต้องการเอาแค่ 5 แถวนแรกของคอลัมน์ Temperature โดยเริ่มจาก index 1 ถึง index 5 (ไม่รวม index 6)
df[["Temperature","Event"]] #ต้องการเอาแค่คอลัมน์ Temperature และ Event ออกมา
df[["Temperature","Event"]][1:7] #ต้องการเอาแค่คอลัมน์ Temperature และ Event ออกมา โดยเอาแค่ 6 แถวแรก โดยเริ่มจาก index 1 ถึง index 6 (ไม่รวม index 7)

            Temperature    Event
Day
2020-12-02           28   เมฆมาก
2020-12-03           27     ฝนตก
2020-12-04           19  แดดร้อน
2020-12-05           20   เมฆมาก
2020-12-06           25     ฝนตก
2020-12-07           36     ฝนตก

## การเลือกแถวและช่วงข้อมูล

In [ ]:
import pandas as pd

df = pd.read_excel("dataupdate.xlsx", sheet_name="weather")
df[1:4] #ต้องการเอาแค่ 3 แถวแรก โดยเริ่มจาก index 1 ถึง index 3 (ไม่รวม index 4)
df[1:5].Temperature #ต้องการเอาแค่คอลัมน์ Temperature ออกมา โดยเอาแค่ 4 แถวแรก โดยเริ่มจาก index 1 ถึง index 4 (ไม่รวม index 5)

1    28
2    27
3    19
4    20
Name: Temperature, dtype: int64

## ถ้า index เป็นข้อความ

In [ ]:
import pandas as pd

df = pd.read_excel("dataupdate.xlsx", sheet_name="weather", index_col="Day")# กำหนดให้ Day เป็น index ของ DataFrame
df.loc["2020-12-02":"2020-12-05"]["Event"] #ต้องการเอาแค่คอลัมน์ Event ออกมา โดยเอาแค่ 4 แถวแรก โดยเริ่มจาก index 2020-12-02 ถึง index 2020-12-05 (ไม่รวม index 2020-12-06) 
#loc คือ โลเคชัน ใช้สำหรับเลือกแถวและคอลัมน์ตามชื่อ index หรือ column name

Day
2020-12-02     เมฆมาก
2020-12-03       ฝนตก
2020-12-04    แดดร้อน
2020-12-05     เมฆมาก
Name: Event, dtype: object

## ค้นหาข้อมูลด้วย Math & Contains
- match(string) ค้นหาคำโดย เริ่มจากอักขระตัวแรก

- contains(string) ค้นหาคำ ไม่จำเป็นต้องเริ่มจากอักขระตัวแรก

In [23]:
import pandas as pd

df = pd.read_excel("dataupdate.xlsx", sheet_name="weather", index_col="Day")# กำหนดให้ Day เป็น index ของ DataFrame
df.Event.str.match("ฝนตก") #คือ การตรวจสอบว่าในคอลัมน์ Event มีคำว่า "ฝนตก" หรือไม่ โดยจะคืนค่าเป็น Series ของ Boolean (True/False) สำหรับแต่ละแถว ต้องมีให้ครบทุกตัวอักขระ
df[df.Event.str.contains("ตก")] #แค่มีบางคำก็ได้ แนะนำ เพราะส่งค่าออกมาทำให้สวยด้วย

            Temperature  WindSpeed Event
Day
2020-12-03           27          4  ฝนตก
2020-12-06           25          6  ฝนตก
2020-12-07           36          4  ฝนตก
2020-12-08           28          6  ฝนตก
2020-12-11           26          4  ฝนตก
2020-12-17           20          8  ฝนตก
2020-12-18           18          5  ฝนตก
2020-12-23           34          3  ฝนตก
2020-12-24           29          4  ฝนตก
2020-12-26           25          8  ฝนตก
2020-12-29           31          1  ฝนตก
2020-12-30           35          2  ฝนตก

## การลูปข้อมูล

มี Function ที่มีชื่อว่า iterrows() เพื่อทำการลูป ก็จะได้ key กับ value มา

In [6]:
import pandas as pd

df = pd.read_excel("dataupdate.xlsx", sheet_name="weather", index_col="Day")
for idx, row in df.iterrows():
    print(f"อุณหภูมิ = {row.Temperature} ส่งผลให้เกิด {row.Event}")

อุณหภูมิ = 30 ส่งผลให้เกิด แดดร้อน
อุณหภูมิ = 28 ส่งผลให้เกิด เมฆมาก
อุณหภูมิ = 27 ส่งผลให้เกิด ฝนตก
อุณหภูมิ = 19 ส่งผลให้เกิด แดดร้อน
อุณหภูมิ = 20 ส่งผลให้เกิด เมฆมาก
อุณหภูมิ = 25 ส่งผลให้เกิด ฝนตก
อุณหภูมิ = 36 ส่งผลให้เกิด ฝนตก
อุณหภูมิ = 28 ส่งผลให้เกิด ฝนตก
อุณหภูมิ = 17 ส่งผลให้เกิด เมฆมาก
อุณหภูมิ = 24 ส่งผลให้เกิด แดดร้อน
อุณหภูมิ = 26 ส่งผลให้เกิด ฝนตก
อุณหภูมิ = 27 ส่งผลให้เกิด แดดร้อน
อุณหภูมิ = 30 ส่งผลให้เกิด แดดร้อน
อุณหภูมิ = 31 ส่งผลให้เกิด เมฆมาก
อุณหภูมิ = 28 ส่งผลให้เกิด แดดร้อน
อุณหภูมิ = 27 ส่งผลให้เกิด แดดร้อน
อุณหภูมิ = 20 ส่งผลให้เกิด ฝนตก
อุณหภูมิ = 18 ส่งผลให้เกิด ฝนตก
อุณหภูมิ = 25 ส่งผลให้เกิด แดดร้อน
อุณหภูมิ = 28 ส่งผลให้เกิด เมฆมาก
อุณหภูมิ = 25 ส่งผลให้เกิด เมฆมาก
อุณหภูมิ = 38 ส่งผลให้เกิด เมฆมาก
อุณหภูมิ = 34 ส่งผลให้เกิด ฝนตก
อุณหภูมิ = 29 ส่งผลให้เกิด ฝนตก
อุณหภูมิ = 34 ส่งผลให้เกิด แดดร้อน
อุณหภูมิ = 25 ส่งผลให้เกิด ฝนตก
อุณหภูมิ = 28 ส่งผลให้เกิด เมฆมาก
อุณหภูมิ = 30 ส่งผลให้เกิด เมฆมาก
อุณหภูมิ = 31 ส่งผลให้เกิด ฝนตก
อุณหภูมิ = 35 ส่งผลให้เกิด ฝนตก

## สอบถามข้อมูลแบบมีเงือนไข

In [15]:
import pandas as pd

df = pd.read_excel("dataupdate.xlsx", sheet_name="weather", index_col="Day")
df[df.Temperature <= 20] #อยากทราบว่าวันใดบ้างที่มีอุณหภมิ น้อยกว่าหรือเท่ากับ 20
df[df.Event == "แดดร้อน"] #อยากทราบว่าวันใดบ้างที่มี อากาศ แดดร้อน
df.loc[(df.Event == "ฝนตก") & (df.Temperature >= 35)] #อยากทราบว่าวันใดบ้างที่มีสภาพอากาศ ฝนตก และ มีอุณหภูมิ มากกว่าหรีอเท่ากับ 35
df.loc[(df.Event == "เมฆมาก") | (df.Temperature <= 18)]
## df.loc[] คือ การรวมฟังก์ชัน

            Temperature  WindSpeed   Event
Day
2020-12-02           28          8  เมฆมาก
2020-12-05           20          5  เมฆมาก
2020-12-09           17          5  เมฆมาก
2020-12-14           31          5  เมฆมาก
2020-12-18           18          5    ฝนตก
2020-12-20           28          4  เมฆมาก
2020-12-21           25          5  เมฆมาก
2020-12-22           38          2  เมฆมาก
2020-12-27           28          9  เมฆมาก
2020-12-28           30          2  เมฆมาก

## การเลือกช่วงข้อมูลด้วย isin(List) ใช้แทน OR

In [ ]:
import pandas as pd

df = pd.read_excel("dataupdate.xlsx", sheet_name="weather", index_col="Day")
df.loc[(df.Temperature.isin([18, 20, 25, 35]))] #ต้องการเอาอุณหภูมิ 18, 20, 25, 35 หรือต้องการเอาข้อมูลหลายตัว จะใช้คำสั่งนี้ ครอบ list[] ให้ด้วย
df.loc[(df.Temperature.isin([20, 35]))] #ต้องการเอาอุณหภูมิ ที่มีค่า 20 และ 35 องศาเซลเซียส เท่านั้น
df.loc[(df.Temperature.isin([30, 35]))][df.Event == "แดดร้อน"] #ต้องการเอาอุณหภูมิ ที่มีค่า 30 และ 35 องศาเซลเซียส และ ต้องการเอาสภาพอากาศที่มี แดดร้อน

/tmp/ipykernel_6770/4034864069.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df.loc[(df.Temperature.isin([30, 35]))][df.Event == "แดดร้อน"]

            Temperature  WindSpeed    Event
Day
2020-12-01           30          9  แดดร้อน
2020-12-13           30          2  แดดร้อน

## เรียงลำดับข้อมูลด้วย Index

In [28]:
import pandas as pd

df = pd.read_excel("Stock.xlsx", index_col="Name")
result = df.sort_index() #เรียงลำดับ ก-ฮ(พยัญชนะ) ไป สระ
##ถ้าอยากเรียนสำหรับ จาก สระไปพยัญชนะ
result = df.sort_index(ascending=False)
result

                             Category  Price  Amount
Name
ไมโครโฟน              เครื่องใช้ไฟฟ้า    750       1
โซฟา                     เฟอร์นิเจอร์   5000       5
โคมไฟ                เครื่องใช้ในบ้าน   1200       7
เสื้อยืดคอกลม                เสื้อผ้า    500       2
เมาส์              อุปกรณ์คอมพิวเตอร์    900      10
เครื่องซักผ้า         เครื่องใช้ไฟฟ้า   3500       0
รถบังคับ                      ของเล่น    500       6
ยางลบ                 อุปกรณ์การเรียน     20       5
ปากกา                 อุปกรณ์การเรียน    200       5
ทีวี                  เครื่องใช้ไฟฟ้า  15000       7
ตุ๊กตาหมีพูห์                 ของเล่น    950       5
จาน                       เครื่องครัว    250       4
คีย์บอร์ด          อุปกรณ์คอมพิวเตอร์    850       5
กางเกงยีนต์                  เสื้อผ้า    999       8
External HardDisk  อุปกรณ์คอมพิวเตอร์   2500       7

## เรียงลำดับข้อมูลด้วย Value

In [ ]:
import pandas as pd

df = pd.read_excel("Stock.xlsx", index_col="Name")
#result = df.sort_values("price") #จากน้อยไปมาก
result = df.sort_values("Price", ascending=False, inplace=True) #จากมากไปน้อย ----- inplace คือ การเซฟทับลงไปเลย
result

                             Category  Price  Amount
Name
ทีวี                  เครื่องใช้ไฟฟ้า  15000       7
โซฟา                     เฟอร์นิเจอร์   5000       5
เครื่องซักผ้า         เครื่องใช้ไฟฟ้า   3500       0
External HardDisk  อุปกรณ์คอมพิวเตอร์   2500       7
โคมไฟ                เครื่องใช้ในบ้าน   1200       7
กางเกงยีนต์                  เสื้อผ้า    999       8
ตุ๊กตาหมีพูห์                 ของเล่น    950       5
เมาส์              อุปกรณ์คอมพิวเตอร์    900      10
คีย์บอร์ด          อุปกรณ์คอมพิวเตอร์    850       5
ไมโครโฟน              เครื่องใช้ไฟฟ้า    750       1
เสื้อยืดคอกลม                เสื้อผ้า    500       2
รถบังคับ                      ของเล่น    500       6
จาน                       เครื่องครัว    250       4
ปากกา                 อุปกรณ์การเรียน    200       5
ยางลบ                 อุปกรณ์การเรียน     20       5

## การเพิ่มคอลัมน์

In [35]:
import pandas as pd

df = pd.read_excel("Stock.xlsx")
df["Delivery"] = 100; #เพิ่มคอลัมน์ delivery โดยนำราคาไปรวมกับค่าขนส่ง

## ทำการเพิ่มคอลัมน์ Total เพิ่อที่จะได้คำนวณได้ว่า ราคา + ค่าส่ง รวมทั้งหมด จะราคากี่บาท

In [37]:
df["Total"] = df["Price"] + df["Delivery"]
df

                 Name            Category  Price  Amount  Delivery  Total
0               เมาส์  อุปกรณ์คอมพิวเตอร์    900      10       100   1000
1               ปากกา     อุปกรณ์การเรียน    200       5       100    300
2               โคมไฟ    เครื่องใช้ในบ้าน   1200       7       100   1300
3            ไมโครโฟน     เครื่องใช้ไฟฟ้า    750       1       100    850
4       เครื่องซักผ้า     เครื่องใช้ไฟฟ้า   3500       0       100   3600
5       เสื้อยืดคอกลม            เสื้อผ้า    500       2       100    600
6         กางเกงยีนต์            เสื้อผ้า    999       8       100   1099
7       ตุ๊กตาหมีพูห์             ของเล่น    950       5       100   1050
8                โซฟา        เฟอร์นิเจอร์   5000       5       100   5100
9                 จาน         เครื่องครัว    250       4       100    350
10               ทีวี     เครื่องใช้ไฟฟ้า  15000       7       100  15100
11              ยางลบ     อุปกรณ์การเรียน     20       5       100    120
12  External HardDisk  อุปกรณ์คอมพิวเตอร์   2500       7       100   2600
13          คีย์บอร์ด  อุปกรณ์คอมพิวเตอร์    850       5       100    950
14           รถบังคับ             ของเล่น    500       6       100    600

## การเปลี่ยนชื่อคอลัมน์

## ต้องสร้างคำสั่งเก็บไว้ในตัวแปร
### cols = {"ชื่อเดิม" : "ชื่อใหม่"}

In [46]:
cols = {"Category" : "Item"}
df.rename(columns=cols, inplace=True) #Inplace save ทับลงไป
df

                 Name                Item  Price  Amount
0               เมาส์  อุปกรณ์คอมพิวเตอร์    900      10
1               ปากกา     อุปกรณ์การเรียน    200       5
2               โคมไฟ    เครื่องใช้ในบ้าน   1200       7
3            ไมโครโฟน     เครื่องใช้ไฟฟ้า    750       1
4       เครื่องซักผ้า     เครื่องใช้ไฟฟ้า   3500       0
5       เสื้อยืดคอกลม            เสื้อผ้า    500       2
6         กางเกงยีนต์            เสื้อผ้า    999       8
7       ตุ๊กตาหมีพูห์             ของเล่น    950       5
8                โซฟา        เฟอร์นิเจอร์   5000       5
9                 จาน         เครื่องครัว    250       4
10               ทีวี     เครื่องใช้ไฟฟ้า  15000       7
11              ยางลบ     อุปกรณ์การเรียน     20       5
12  External HardDisk  อุปกรณ์คอมพิวเตอร์   2500       7
13          คีย์บอร์ด  อุปกรณ์คอมพิวเตอร์    850       5
14           รถบังคับ             ของเล่น    500       6

## การเปลี่ยนชื่อแบบที่เดียว หลายๆ คอลัมน์

In [48]:
recols = {"Item" : "Category", "Price" : "Cost", "Amount" : "Quanity"}
df.rename(columns=recols, inplace=True)
df

                 Name            Category   Cost  Quanity
0               เมาส์  อุปกรณ์คอมพิวเตอร์    900       10
1               ปากกา     อุปกรณ์การเรียน    200        5
2               โคมไฟ    เครื่องใช้ในบ้าน   1200        7
3            ไมโครโฟน     เครื่องใช้ไฟฟ้า    750        1
4       เครื่องซักผ้า     เครื่องใช้ไฟฟ้า   3500        0
5       เสื้อยืดคอกลม            เสื้อผ้า    500        2
6         กางเกงยีนต์            เสื้อผ้า    999        8
7       ตุ๊กตาหมีพูห์             ของเล่น    950        5
8                โซฟา        เฟอร์นิเจอร์   5000        5
9                 จาน         เครื่องครัว    250        4
10               ทีวี     เครื่องใช้ไฟฟ้า  15000        7
11              ยางลบ     อุปกรณ์การเรียน     20        5
12  External HardDisk  อุปกรณ์คอมพิวเตอร์   2500        7
13          คีย์บอร์ด  อุปกรณ์คอมพิวเตอร์    850        5
14           รถบังคับ             ของเล่น    500        6

## การลบคอลัมน์

In [53]:
import pandas as pd

df = pd.read_excel("Stock.xlsx")
df.drop("Amount",axis=1, inplace=True) #axis=1 คือ คอลัมน์
df

                 Name            Category  Price
0               เมาส์  อุปกรณ์คอมพิวเตอร์    900
1               ปากกา     อุปกรณ์การเรียน    200
2               โคมไฟ    เครื่องใช้ในบ้าน   1200
3            ไมโครโฟน     เครื่องใช้ไฟฟ้า    750
4       เครื่องซักผ้า     เครื่องใช้ไฟฟ้า   3500
5       เสื้อยืดคอกลม            เสื้อผ้า    500
6         กางเกงยีนต์            เสื้อผ้า    999
7       ตุ๊กตาหมีพูห์             ของเล่น    950
8                โซฟา        เฟอร์นิเจอร์   5000
9                 จาน         เครื่องครัว    250
10               ทีวี     เครื่องใช้ไฟฟ้า  15000
11              ยางลบ     อุปกรณ์การเรียน     20
12  External HardDisk  อุปกรณ์คอมพิวเตอร์   2500
13          คีย์บอร์ด  อุปกรณ์คอมพิวเตอร์    850
14           รถบังคับ             ของเล่น    500